[GLOBAL]
pants_version = "2.29.0"
level = "info"
colors = true

# Enable Python backends
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.12.*"]
enable_resolves = true
default_resolve = "python-default"

[python-infer]
imports = true
init_files = "always"

[python.resolves]
python-default = "python-default.lock"


[black]
args = ["--line-length=100"]

[pytest]
args = ["-v"]

[mypy]
args = ["--strict", "--ignore-missing-imports"]