"""add_foreign_key_user_account

Revision ID: 5a7d9b5e54cd
Revises: ac7b8ff1dc83
Create Date: 2025-10-27 18:08:46.353449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7d9b5e54cd'
down_revision: Union[str, None] = 'ac7b8ff1dc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    # ### end Alembic commands ###

