"""add_funded_transfer_and_funding_step_tables

Revision ID: 8787f9df07f1
Revises: cf8570ccd66c
Create Date: 2025-12-21 18:07:48.225371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8787f9df07f1'
down_revision: Union[str, None] = 'cf8570ccd66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funded_transfers', sa.Column('payout_provider', sa.String(), nullable=True))
    op.add_column('funded_transfers', sa.Column('payout_reference', sa.String(), nullable=True))
    op.create_index(op.f('ix_funded_transfers_payout_reference'), 'funded_transfers', ['payout_reference'], unique=False)
    op.drop_column('funded_transfers', 'payout_provider_id')
    op.add_column('funding_steps', sa.Column('provider_name', sa.String(), nullable=True))
    op.add_column('funding_steps', sa.Column('provider_debit_id', sa.String(), nullable=True))
    op.add_column('funding_steps', sa.Column('provider_reference', sa.String(), nullable=True))
    op.drop_index('ix_funding_steps_mono_debit_id', table_name='funding_steps')
    op.drop_index('ix_funding_steps_mono_reference', table_name='funding_steps')
    op.create_index(op.f('ix_funding_steps_provider_debit_id'), 'funding_steps', ['provider_debit_id'], unique=False)
    op.create_index(op.f('ix_funding_steps_provider_reference'), 'funding_steps', ['provider_reference'], unique=True)
    op.drop_column('funding_steps', 'mono_debit_id')
    op.drop_column('funding_steps', 'mono_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_steps', sa.Column('mono_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('funding_steps', sa.Column('mono_debit_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_funding_steps_provider_reference'), table_name='funding_steps')
    op.drop_index(op.f('ix_funding_steps_provider_debit_id'), table_name='funding_steps')
    op.create_index('ix_funding_steps_mono_reference', 'funding_steps', ['mono_reference'], unique=False)
    op.create_index('ix_funding_steps_mono_debit_id', 'funding_steps', ['mono_debit_id'], unique=False)
    op.drop_column('funding_steps', 'provider_reference')
    op.drop_column('funding_steps', 'provider_debit_id')
    op.drop_column('funding_steps', 'provider_name')
    op.add_column('funded_transfers', sa.Column('payout_provider_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_funded_transfers_payout_reference'), table_name='funded_transfers')
    op.drop_column('funded_transfers', 'payout_reference')
    op.drop_column('funded_transfers', 'payout_provider')
    # ### end Alembic commands ###

