"""clean_up_models

Revision ID: b680bc1afbd2
Revises: 5a7d9b5e54cd
Create Date: 2025-10-27 18:52:06.272122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b680bc1afbd2'
down_revision: Union[str, None] = '5a7d9b5e54cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.drop_column('accounts', 'is_active')
    op.drop_column('accounts', 'account_title')
    op.drop_column('accounts', 'linked_at')
    op.drop_index('ix_users_whatsapp_id', table_name='users')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'whatsapp_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_users_whatsapp_id', 'users', ['whatsapp_id'], unique=False)
    op.add_column('accounts', sa.Column('linked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('account_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'is_default')
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###

