"""make_beneficiary_fields_nullable

Revision ID: cf8570ccd66c
Revises: add_beneficiary_type_001
Create Date: 2025-11-20 21:59:06.017423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cf8570ccd66c'
down_revision: Union[str, None] = 'add_beneficiary_type_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make beneficiary fields nullable to avoid saving inappropriate data for airtime beneficiaries
    op.alter_column('beneficiaries', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('beneficiaries', 'bank_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('beneficiaries', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beneficiaries', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('beneficiaries', 'bank_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('beneficiaries', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

