"""update_user_account

Revision ID: 943a970cf4a9
Revises: b680bc1afbd2
Create Date: 2025-10-27 23:17:09.861354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943a970cf4a9'
down_revision: Union[str, None] = 'b680bc1afbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_status')
    # ### end Alembic commands ###

