"""add_provider_status_to_transactions

Revision ID: 5a0ff498d6ee
Revises: 00e286a3f3c4
Create Date: 2025-12-30 15:14:55.526406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0ff498d6ee'
down_revision: Union[str, None] = '00e286a3f3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('provider_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('provider_error_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'provider_error_code')
    op.drop_column('transactions', 'provider_status')
    # ### end Alembic commands ###

