"""add_actionable_message_table

Revision ID: 00e286a3f3c4
Revises: 8787f9df07f1
Create Date: 2025-12-26 07:57:44.745481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e286a3f3c4'
down_revision: Union[str, None] = '8787f9df07f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionable_messages', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('actionable_messages', sa.Column('wa_message_id', sa.String(), nullable=False))
    op.add_column('actionable_messages', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_index('ix_actionable_messages_message_id', table_name='actionable_messages')
    op.create_index(op.f('ix_actionable_messages_expires_at'), 'actionable_messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_actionable_messages_user_id'), 'actionable_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_actionable_messages_wa_message_id'), 'actionable_messages', ['wa_message_id'], unique=True)
    op.create_foreign_key('fk_actionable_messages_user_id', 'actionable_messages', 'users', ['user_id'], ['id'])
    op.drop_column('actionable_messages', 'message_id')
    op.drop_column('actionable_messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionable_messages', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('actionable_messages', sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_actionable_messages_user_id', 'actionable_messages', type_='foreignkey')
    op.drop_index(op.f('ix_actionable_messages_wa_message_id'), table_name='actionable_messages')
    op.drop_index(op.f('ix_actionable_messages_user_id'), table_name='actionable_messages')
    op.drop_index(op.f('ix_actionable_messages_expires_at'), table_name='actionable_messages')
    op.create_index('ix_actionable_messages_message_id', 'actionable_messages', ['message_id'], unique=False)
    op.drop_column('actionable_messages', 'expires_at')
    op.drop_column('actionable_messages', 'wa_message_id')
    op.drop_column('actionable_messages', 'user_id')
    # ### end Alembic commands ###

