"""create_beneficiary_table

Revision ID: 940b5c5ee7e8
Revises: 3cdb492c77dc
Create Date: 2025-11-02 19:48:22.016585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940b5c5ee7e8'
down_revision: Union[str, None] = '3cdb492c77dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('account_name', sa.String(), nullable=False))
    op.add_column('beneficiaries', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('beneficiaries', sa.Column('bank_code', sa.String(), nullable=False))
    op.add_column('beneficiaries', sa.Column('bank_name', sa.String(), nullable=False))
    op.add_column('beneficiaries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('beneficiaries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('beneficiaries', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('beneficiaries', 'updated_at')
    op.drop_column('beneficiaries', 'created_at')
    op.drop_column('beneficiaries', 'bank_name')
    op.drop_column('beneficiaries', 'bank_code')
    op.drop_column('beneficiaries', 'alias')
    op.drop_column('beneficiaries', 'account_name')
    # ### end Alembic commands ###

