"""add faq_entries table

Revision ID: e3d1b248da69
Revises: 5a0ff498d6ee
Create Date: 2026-01-05 14:50:39.948050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d1b248da69'
down_revision: Union[str, None] = '5a0ff498d6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_category'), 'faq_entries', ['category'], unique=False)
    op.create_index(op.f('ix_faq_entries_id'), 'faq_entries', ['id'], unique=False)
    op.create_index(op.f('ix_faq_entries_is_active'), 'faq_entries', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_entries_is_active'), table_name='faq_entries')
    op.drop_index(op.f('ix_faq_entries_id'), table_name='faq_entries')
    op.drop_index(op.f('ix_faq_entries_category'), table_name='faq_entries')
    op.drop_table('faq_entries')
    # ### end Alembic commands ###

