"""Add UserChannelIdentity model

Revision ID: b0b97c21eefc
Revises: 360592035fb5
Create Date: 2026-02-22 16:36:30.873539

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0b97c21eefc"
down_revision: str | None = "360592035fb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_channel_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("channel_user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_channel_identities_user_id", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "channel_user_id", name="uq_user_channel_identity"),
    )
    op.create_index(
        op.f("ix_user_channel_identities_channel_user_id"), "user_channel_identities", ["channel_user_id"], unique=False
    )
    op.create_index(op.f("ix_user_channel_identities_id"), "user_channel_identities", ["id"], unique=False)
    op.create_index(op.f("ix_user_channel_identities_user_id"), "user_channel_identities", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_channel_identities_user_id"), table_name="user_channel_identities")
    op.drop_index(op.f("ix_user_channel_identities_id"), table_name="user_channel_identities")
    op.drop_index(op.f("ix_user_channel_identities_channel_user_id"), table_name="user_channel_identities")
    op.drop_table("user_channel_identities")
    # ### end Alembic commands ###
