"""rename_wa_message_id_to_channel_message_id

Revision ID: 276932c56c73
Revises: b0b97c21eefc
Create Date: 2026-02-24 01:33:52.011799

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "276932c56c73"
down_revision: str | None = "b0b97c21eefc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("actionable_messages", "wa_message_id", new_column_name="channel_message_id")
    op.drop_index(op.f("ix_actionable_messages_wa_message_id"), table_name="actionable_messages")
    op.create_index(
        op.f("ix_actionable_messages_channel_message_id"), "actionable_messages", ["channel_message_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("actionable_messages", "channel_message_id", new_column_name="wa_message_id")
    op.drop_index(op.f("ix_actionable_messages_channel_message_id"), table_name="actionable_messages")
    op.create_index(op.f("ix_actionable_messages_wa_message_id"), "actionable_messages", ["wa_message_id"], unique=True)
    # ### end Alembic commands ###
