"""ïnitial-schema

Revision ID: 27cf02debf98
Revises:
Create Date: 2026-01-12 09:55:30.425389

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27cf02debf98"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faq_entries_category"), "faq_entries", ["category"], unique=False)
    op.create_index(op.f("ix_faq_entries_id"), "faq_entries", ["id"], unique=False)
    op.create_index(op.f("ix_faq_entries_is_active"), "faq_entries", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("mono_customer_id", sa.String(), nullable=True),
        sa.Column("onboarding_status", sa.String(), nullable=True),
        sa.Column("last_active", sa.DateTime(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("transaction_pin", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_mono_customer_id"), "users", ["mono_customer_id"], unique=False)
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=False),
        sa.Column("bank_code", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("mandate_id", sa.String(), nullable=True),
        sa.Column("mandate_status", sa.String(), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_accounts_user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
    )
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_index(op.f("ix_accounts_mandate_id"), "accounts", ["mandate_id"], unique=False)
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "actionable_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("wa_message_id", sa.String(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("message_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_actionable_messages_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actionable_messages_expires_at"), "actionable_messages", ["expires_at"], unique=False)
    op.create_index(op.f("ix_actionable_messages_id"), "actionable_messages", ["id"], unique=False)
    op.create_index(op.f("ix_actionable_messages_message_type"), "actionable_messages", ["message_type"], unique=False)
    op.create_index(op.f("ix_actionable_messages_user_id"), "actionable_messages", ["user_id"], unique=False)
    op.create_index(op.f("ix_actionable_messages_wa_message_id"), "actionable_messages", ["wa_message_id"], unique=True)
    op.create_table(
        "beneficiaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("beneficiary_type", sa.String(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("bank_code", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_beneficiaries_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beneficiaries_beneficiary_type"), "beneficiaries", ["beneficiary_type"], unique=False)
    op.create_index(op.f("ix_beneficiaries_id"), "beneficiaries", ["id"], unique=False)
    op.create_index(op.f("ix_beneficiaries_user_id"), "beneficiaries", ["user_id"], unique=False)
    op.create_table(
        "funded_transfers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("recipient_account_number", sa.String(), nullable=False),
        sa.Column("recipient_bank_code", sa.String(), nullable=False),
        sa.Column("recipient_bank_name", sa.String(), nullable=False),
        sa.Column("recipient_name", sa.String(), nullable=False),
        sa.Column("narration", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payout_provider", sa.String(), nullable=True),
        sa.Column("payout_reference", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("payout_retry_count", sa.Integer(), nullable=False),
        sa.Column("max_payout_retries", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("funding_completed_at", sa.DateTime(), nullable=True),
        sa.Column("payout_initiated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_funded_transfers_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funded_transfers_created_at"), "funded_transfers", ["created_at"], unique=False)
    op.create_index(op.f("ix_funded_transfers_id"), "funded_transfers", ["id"], unique=False)
    op.create_index(op.f("ix_funded_transfers_idempotency_key"), "funded_transfers", ["idempotency_key"], unique=True)
    op.create_index(
        op.f("ix_funded_transfers_payout_reference"), "funded_transfers", ["payout_reference"], unique=False
    )
    op.create_index(op.f("ix_funded_transfers_status"), "funded_transfers", ["status"], unique=False)
    op.create_index(op.f("ix_funded_transfers_user_id"), "funded_transfers", ["user_id"], unique=False)
    op.create_table(
        "funding_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("funded_transfer_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=True),
        sa.Column("provider_debit_id", sa.String(), nullable=True),
        sa.Column("provider_reference", sa.String(), nullable=True),
        sa.Column("initiated_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("refunded_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], name="fk_funding_steps_account_id"),
        sa.ForeignKeyConstraint(
            ["funded_transfer_id"], ["funded_transfers.id"], name="fk_funding_steps_funded_transfer_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funding_steps_account_id"), "funding_steps", ["account_id"], unique=False)
    op.create_index(op.f("ix_funding_steps_funded_transfer_id"), "funding_steps", ["funded_transfer_id"], unique=False)
    op.create_index(op.f("ix_funding_steps_id"), "funding_steps", ["id"], unique=False)
    op.create_index(op.f("ix_funding_steps_provider_debit_id"), "funding_steps", ["provider_debit_id"], unique=False)
    op.create_index(op.f("ix_funding_steps_provider_reference"), "funding_steps", ["provider_reference"], unique=True)
    op.create_index(op.f("ix_funding_steps_status"), "funding_steps", ["status"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("source_account_number", sa.String(), nullable=False),
        sa.Column("source_bank_name", sa.String(), nullable=False),
        sa.Column("recipient_account_number", sa.String(), nullable=False),
        sa.Column("recipient_bank_code", sa.String(), nullable=False),
        sa.Column("recipient_bank_name", sa.String(), nullable=False),
        sa.Column("recipient_name", sa.String(), nullable=False),
        sa.Column("narration", sa.String(), nullable=True),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("provider_response", sa.JSON(), nullable=True),
        sa.Column("provider_status", sa.String(), nullable=True),
        sa.Column("provider_error_code", sa.String(), nullable=True),
        sa.Column("receipt_sent", sa.Boolean(), nullable=False),
        sa.Column("beneficiary_suggested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["source_account_id"], ["accounts.id"], name="fk_transactions_source_account_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_transactions_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(op.f("ix_transactions_idempotency_key"), "transactions", ["idempotency_key"], unique=True)
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_funding_steps_status"), table_name="funding_steps")
    op.drop_index(op.f("ix_funding_steps_provider_reference"), table_name="funding_steps")
    op.drop_index(op.f("ix_funding_steps_provider_debit_id"), table_name="funding_steps")
    op.drop_index(op.f("ix_funding_steps_id"), table_name="funding_steps")
    op.drop_index(op.f("ix_funding_steps_funded_transfer_id"), table_name="funding_steps")
    op.drop_index(op.f("ix_funding_steps_account_id"), table_name="funding_steps")
    op.drop_table("funding_steps")
    op.drop_index(op.f("ix_funded_transfers_user_id"), table_name="funded_transfers")
    op.drop_index(op.f("ix_funded_transfers_status"), table_name="funded_transfers")
    op.drop_index(op.f("ix_funded_transfers_payout_reference"), table_name="funded_transfers")
    op.drop_index(op.f("ix_funded_transfers_idempotency_key"), table_name="funded_transfers")
    op.drop_index(op.f("ix_funded_transfers_id"), table_name="funded_transfers")
    op.drop_index(op.f("ix_funded_transfers_created_at"), table_name="funded_transfers")
    op.drop_table("funded_transfers")
    op.drop_index(op.f("ix_beneficiaries_user_id"), table_name="beneficiaries")
    op.drop_index(op.f("ix_beneficiaries_id"), table_name="beneficiaries")
    op.drop_index(op.f("ix_beneficiaries_beneficiary_type"), table_name="beneficiaries")
    op.drop_table("beneficiaries")
    op.drop_index(op.f("ix_actionable_messages_wa_message_id"), table_name="actionable_messages")
    op.drop_index(op.f("ix_actionable_messages_user_id"), table_name="actionable_messages")
    op.drop_index(op.f("ix_actionable_messages_message_type"), table_name="actionable_messages")
    op.drop_index(op.f("ix_actionable_messages_id"), table_name="actionable_messages")
    op.drop_index(op.f("ix_actionable_messages_expires_at"), table_name="actionable_messages")
    op.drop_table("actionable_messages")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_mandate_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_mono_customer_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_faq_entries_is_active"), table_name="faq_entries")
    op.drop_index(op.f("ix_faq_entries_id"), table_name="faq_entries")
    op.drop_index(op.f("ix_faq_entries_category"), table_name="faq_entries")
    op.drop_table("faq_entries")
    # ### end Alembic commands ###
